project:
  type: website
  output-dir: _output
  title: "MNIST Neural Network Explorer"
  render:
    - "*.qmd"
  resources:
    - "*.png"
    - "*.jpg"
    - "*.css"

website:
  title: "MNIST Neural Network Explorer"
  navbar:
    logo: "assets/logo.png"
    left:
      - href: index.qmd
        text: Home
      - href: data-exploration.qmd
        text: Data Exploration
      - href: methodology.qmd
        text: Methodology
      - href: results.qmd
        text: Results
      - href: model-analysis.qmd
        text: Model Analysis
      - href: interactive-demo.qmd
        text: Interactive Demo
      - href: team.qmd
        text: Team
  page-footer:
    center: 
      - text: "© 2023 MNIST Neural Network Explorer"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true 