# Project options - can change the overall project title
# and the name of the output directory here
# Uncomment the post-render command to use the 
# return-to-source post script - see Readme
project:
  title: "MNIST Training Experiment"
  output-dir: "_output"
  type: website
  preview:
    port: 8888
    browser: false

# 包含子项目配置
resources:
  - "project-page/**/*"
  - "arxiv-article/**/*"

# options for all formats - suggested not to change
from: markdown+raw_attribute+raw_tex
standalone: true
self-contained: true
slide-level: 2

# Navigation structure
website:
  title: "MNIST Training Experiment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: contributing.md
        text: Contributing
      - text: "Demo Pages"
        menu:
          - text: "Project Page"
            href: "project-page/index.html"
          - text: "arXiv Article"
            href: "arxiv-article/arxiv-article.html"
    tools:
      - icon: github
        href: https://github.com/Jing-yilin/mnist