project:
  type: website
  output-dir: _output
  title: "MNIST Neural Network Explorer"

navbar:
  background: primary
  left:
    - text: "Project Website"
      href: project-page/index.html
    - text: "Research Paper"
      href: arxiv-article/index.html
  right:
    - icon: github
      href: https://github.com/Jing-yilin/mnist

page-footer:
  center: 
    - text: "© 2025 MNIST Neural Network Explorer"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false 