# Project options - can change the overall project title
# and the name of the output directory here
# Uncomment the post-render command to use the 
# return-to-source post script - see Readme
project:
  title: "MNIST Training Experiment"
  output-dir: "_output"

# options for all formats - suggested not to change
from: markdown+raw_attribute+raw_tex
standalone: true
self-contained: true
slide-level: 2

# Navigation structure
website:
  title: "MNIST Training Experiment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: usage.md
        text: Usage
      - href: api.md
        text: API
      - href: contributing.md
        text: Contributing
    tools:
      - icon: github
        href: https://github.com/your-username/mnist