project:
  type: website
  output-dir: _site
  title: "MNIST Data Explorer"
  render:
    - "*.qmd"
  resources:
    - "*.png"
    - "*.jpg"

website:
  title: "MNIST Data Explorer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data-exploration.qmd
        text: Data Exploration
      - href: model-analysis.qmd
        text: Model Analysis
  repo-url: https://github.com/Jing-yilin/mnist
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 