name: Publish Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # Required for correctly handling git history
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2.0.0
        with:
          version: 1.3.450  # Specify the Quarto version
      
      # Install Quarto extensions
      - name: Install Quarto extensions
        run: |
          cd docs
          quarto add quarto-ext/fontawesome
          quarto add grantmcdermott/quarto-revealjs-clean
          quarto add mikemahoney218/quarto-arxiv
      
      # Render the main documentation
      - name: Render main docs
        run: |
          cd docs
          quarto render
      
      # Render the project page separately
      - name: Render project page
        run: |
          cd docs/project-page
          quarto render index.md --to html

      # Render the arXiv article
      - name: Render arXiv article
        run: |
          cd docs/arxiv-article
          quarto render
      
      # Create directory structure for deployment
      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          cp -r docs/_output/* _site/
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: _site
          branch: gh-pages
          clean: true  # Automatically remove deleted files from the deployment branch
      
      # Create artifact with documentation files
      - name: Archive documentation
        uses: actions/upload-artifact@v4.3.1
        with:
          name: documentation
          path: _site
          retention-days: 30 