name: Publish Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for correctly handling git history
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450  # Specify the Quarto version
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter matplotlib pandas numpy

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.44.0
      
      - name: Install Quarto extensions
        run: |
          cd docs
          quarto add quarto-ext/fontawesome
          quarto add grantmcdermott/quarto-revealjs-clean
          quarto add mikemahoney218/quarto-arxiv
      
      # Render the main documentation
      - name: Render main docs
        run: |
          cd docs
          quarto render
      
      # Render the project page separately
      - name: Render project page
        run: |
          cd docs/project-page
          quarto render

      # Render the arXiv article
      - name: Render arXiv article
        run: |
          cd docs/arxiv-article
          quarto render
      
      # Create directory structure for deployment
      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          cp -r docs/_output/* _site/
          mkdir -p _site/project-page
          cp -r docs/project-page/_site/* _site/project-page/
          mkdir -p _site/arxiv-article
          cp -r docs/arxiv-article/_site/* _site/arxiv-article/
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean: true  # Automatically remove deleted files from the deployment branch
      
      # Create artifact with documentation files
      - name: Archive documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: _site
          retention-days: 30 